apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: workshop-rht-app
spec:
  # Use service account with git and image repo credentials
  serviceAccountName: pipeline
  pipelineRef: 
    name: workshop-rht-app
  params:
  - name: URL
    value: https://github.com/mgohashi/workshop-rht-app.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/test-app/workshop-rht-app
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: maven-settings
    configMap:
      name: maven-settings